name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when pushing to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    permissions:
      contents: write  # Allow the workflow to write to the repository
      pages: write     # Allow the workflow to push to the gh-pages branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # GitHub Pages deployment action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's token for authentication
          publish_dir: ./  # Path to the folder you want to deploy (root in your case)
