name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # This will deploy on every push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # GitHub Pages deployment action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's token for authentication
          publish_dir: ./  # Publish from the root directory (where your HTML, CSS, JS files are)
